sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind
after_success:
  - cd test && bash <(curl -s https://codecov.io/bash)
env:
  matrix:
   - BUILD_CXX=0 CFLAGS="--coverage"
   - BUILD_CXX=1 CFLAGS="--coverage"
   - BUILD_CXX=0 CFLAGS="-O3"
   - BUILD_CXX=1 CFLAGS="-O3"
   - BUILD_CXX=0 TESTRUN_WRAPPER='valgrind -q --error-exitcode=126 --track-origins=yes --leak-check=full' CFLAGS="-O1 -g3" TESTRUN_NAME=memcheck
   - BUILD_CXX=1 TESTRUN_WRAPPER='valgrind -q --error-exitcode=126 --track-origins=yes --leak-check=full' CFLAGS="-O1 -g3" TESTRUN_NAME=memcheck
script:
 - make -C test clean && make -j$(nproc) -C test
